steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testmlops-446623/regression-model1', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testmlops-446623/regression-model1']

- name: 'gcr.io/testmlops-446623/regression-model1'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python main.py & python -m pytest
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'regression-model'
   - '--image'
   - 'gcr.io/testmlops-446623/regression-model1'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
images:
- 'gcr.io/testmlops-446623/regression-model1'

options:
  logging: CLOUD_LOGGING_ONLY